name: powersync_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

# Add regular dependencies here.

dev_dependencies:
  lints: ^2.1.1
  melos: ^6.2.0
  test: ^1.25.0
  path: ^1.0.0
  yaml: ^3.1.2
  interact: ^2.1.1
