name: powersync_attachments_helper
description: A helper library for handling attachments when using PowerSync.
version: 0.1.0
homepage: https://www.powersync.com/
repository: https://github.com/powersync-ja/powersync-dart/packages/powersync_attachments_helper.dart

environment:
  sdk: ^3.2.3

dependencies:
  powersync: ^1.0.0
  logging: ^1.2.0
  sqlite_async: ^0.5.2
  path_provider: ^2.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
