name: powersync
version: 1.2.2
homepage: https://powersync.com
repository: https://github.com/powersync-ja/powersync.dart
description: PowerSync Flutter SDK - keep PostgreSQL databases in sync with on-device SQLite databases.
environment:
  sdk: ^3.2.3
dependencies:
  # Needed because of sqlite3_flutter_libs
  flutter:
    sdk: flutter

  sqlite_async: ^0.6.0
  sqlite3_flutter_libs: ^0.5.15
  http: ^1.1.0
  uuid: ^4.2.0
  async: ^2.10.0
  logging: ^1.1.1
  collection: ^1.17.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  test_api: ^0.7.0
  path_provider: ^2.0.13
  sqlite3: ^2.3.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  path: ^1.8.3

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
