name: powersync
version: 1.8.6
homepage: https://powersync.com
repository: https://github.com/powersync-ja/powersync.dart
description: PowerSync Flutter SDK - sync engine for building local-first apps.
environment:
  sdk: ^3.4.0
dependencies:
  # Needed because of sqlite3_flutter_libs
  flutter:
    sdk: flutter

  sqlite3_flutter_libs: ^0.5.23
  powersync_core: ^0.1.0
dev_dependencies:
  lints: ^3.0.0
  path: ^1.8.3
  path_provider: ^2.0.13

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
