name: Demos checks

concurrency:
  group: demos-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Install Melos
        run: flutter pub global activate melos
      - name: Install dependencies
        run: melos bootstrap
      - name: Check formatting
        run: melos format:check:demos
      - name: Lint
        run: |
          ./.github/workflows/scripts/copy-config.sh
          melos analyze:demos

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
      - name: Install melos
        run: flutter pub global activate melos
      - name: Install dependencies
        run: melos bootstrap
      - name: Download powersync binary
        run: |
          github="https://github.com/powersync-ja/powersync-sqlite-core/releases/download/v0.1.6"

          curl "${github}/libpowersync_x64.so" -o packages/powersync/libpowersync.so --create-dirs -L -f
      - name: Run tests
        run: melos test
