name: Demos checks

concurrency:
  group: demos-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Install Melos
        run: flutter pub global activate melos
      - name: Install dependencies
        run: melos prepare
      - name: Check formatting
        run: melos format:check:demos
      - name: Lint
        run: |
          ./.github/workflows/scripts/copy-config.sh
          melos analyze:demos

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
      - name: Install melos
        run: flutter pub global activate melos
      - name: Install dependencies
        run: melos prepare
      - name: Run flutter tests
        run: melos test
      - name: Run dart tests
        run: melos test:web
