name: Packages check

concurrency:
    group: packages-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install Melos
        run: flutter pub global activate melos
      - name: Install dependencies
        run: melos bootstrap
      - name: Check formatting
        run: melos format:check:packages
      - name: Lint
        run: melos analyze:packages
      - name: Publish dry-run
        run: melos publish --dry-run --yes
      - name: Check publish score
        run: |
          flutter pub global activate pana
          ./.github/workflows/scripts/run-pana.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - name: Install melos
        run: flutter pub global activate melos
      - name: Install dependencies
        run: melos bootstrap
      - name: Install WASM SQLite
        run: |
          mkdir -p packages/powersync/assets/ && curl -LJ https://github.com/simolus3/sqlite3.dart/releases/download/sqlite3-2.3.0/sqlite3.wasm -o packages/powersync/assets/sqlite3.wasm

      - name: Compile WebWorker
        run:  dart compile js -o packages/powersync/assets/drift_worker.js -O0 packages/powersync/lib/src/web/powersync_db.worker.dart

      - name: Run tests
        run: melos test
