# This triggers whenever a tagged release is pushed
name: Compile Assets and Create Draft Release

on:
  push:
    tags:
      - "powersync-v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Install Dependencies and Compile Assets
        run: melos prepare

      - name: Create Draft Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          tag="${{ github.ref_name }}"
          body="Release $tag"
          gh release create --draft "$tag" --title "$tag" --notes "$body" --generate-notes
          gh release upload "${{ github.ref_name }}" packages/powersync/assets/powersync_db.worker.js packages/powersync/assets/powersync_sync.worker.js
